kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: xkcd
  namespace: test
spec:
  scaleTargetRef:
    deployment: xkcd
    service: xkcd
    port: 8080
  replicas:
    min: 1
    max: 10
